spring:
  application:
    name: saasPlatform
  profiles:
    active: dev
  server:
    port: 8080
resilience4j:
  ratelimiter:
    instances:
      global-api:
        limit-for-period: 1000
        limit-refresh-period: 1s
        timeout-duration: 0


